### ISSUE TITLE
SearchBox text remains forever

### ISSUE THREAD

**Issue by akanksh1997** [anehx/anonboard-frontend#4]
![nav-view](https://cloud.githubusercontent.com/assets/9280537/14708749/2015a108-07cd-11e6-88e8-6b73a0c81556.JPG)

The searchBox should get cleared after navigating through the website and reopening the navigation.

**Comment by anehx** [comment]
I think it sould only be cleared after a transition to another URL. If they close the navigation and still have a search left they may want it to persist? @akanksh1997

**Comment by akanksh1997** [comment]
Once you search for a topic, you might create some new threads or comments. It doesn't seem to be user-friendly to me if I want to navigate to another topic later and need to delete the text in the searchBox first .. @anehx

**Comment by anehx** [comment]
Well, seems fair. So on close and on transition - clear the search.. @akanksh1997
