### ISSUE TITLE
Validation while creating a new thread

### ISSUE THREAD

**Issue by akanksh1997** [anehx/anonboard-frontend#5]
![new-thread-validation](https://cloud.githubusercontent.com/assets/9280537/14709296/3871fd98-07d0-11e6-9a83-0931ff64e02c.JPG)

The same error is displayed multiple times as you hit the saveButton x times while leaving the textBoxes empty.
I don't think there is a sequence behind it. Got approx. 5min to force the error again as I missed it once. Also a error "This field may not be null" appeared while leaving the textBoxes empty (unfortunately missed the error as I was hitting the button crazy af).

**Comment by akanksh1997** [comment]
Was able to force the "null" error finally.. here you go.. @anehx 
![new-thread-validation](https://cloud.githubusercontent.com/assets/9280537/14710051/22721e84-07d4-11e6-9cd5-f73300d883ea.JPG)

**Comment by anehx** [comment]
Note to myself: use http://offirgolan.github.io/ember-cp-validations/ for frontend validation
